# Sovereignty Configuration

# Database Configuration
database:
  # Database type: mysql or sqlite
  type: sqlite

  # MySQL Configuration
  mysql:
    host: localhost
    port: 3306
    database: sovereignty
    username: root
    password: password
    useSSL: false

  # SQLite Configuration
  sqlite:
    filename: sovereignty.db

# Language settings (available: en_US)
language: en_US

# Power Scaling Configuration
power-scaling:
  # Max chunks by power level
  chunks:
    level-1: 10
    level-2: 25
    level-3: 50
    level-4: 80
    level-5: 120
    level-6: 180

  # Max soldier lives by power level
  soldier-lives:
    level-1: 5
    level-2: 10
    level-3: 20
    level-4: 30
    level-5: 50
    level-6: 75

# War Configuration
war:
  # Allow destruction of blocks in enemy territory during war
  enable-destruction: false

  # Enable assassination mode (killing president instantly wins war)
  enable-assassination: false

  # Percentage of chunks to annex from loser after war (0.0-1.0)
  annexation-percentage: 0.25

  # How often power should recalculate (in minutes)
  power-recalculation-interval: 10

# Vault Configuration
vaults:
  # Base number of rows in nation vault (1 row = 9 slots)
  base-vault-rows: 6

  # Additional rows added per power level
  additional-rows-per-level: 6

  # Maximum number of vault pages
  max-pages: 10

  # Number of rows in nation vault (1 row = 9 slots) - legacy setting
  nation-vault-rows: 3

  # Number of rows in trade vault (1 row = 9 slots)
  trade-vault-rows: 3

  # How long expired items remain before automatic deletion (in minutes)
  expired-items-time-minutes: 1440 # 24 hours
