name: Sovereignty
version: "${version}"
main: com.tatayless.sovereignty.Sovereignty
api-version: "1.21.5"
authors:
  - Tatayless
description: A nation-based land claiming and war plugin
commands:
  nation:
    description: Main nation command
    usage: /nation <subcommand>
    aliases: [n]
  war:
    description: War management commands
    usage: /war <subcommand>
  vault:
    description: Access nation vault
    usage: /vault
permissions:
  sovereignty.admin.bypass:
    description: Bypass protection
    default: op
  sovereignty.admin.chunks:
    description: Claim more chunks than allowed
    default: op
  sovereignty.admin.wars:
    description: Cancel ongoing wars
    default: op
