name: Sovereignty
version: ${version}
main: com.tatayless.sovereignty.Sovereignty
api-version: "1.20"
description: ${description}
author: tatayless
commands:
  sovereignty:
    description: Main command for Sovereignty plugin
    usage: /sovereignty <subcommand>
    aliases: [sov]
permissions:
  sovereignty.admin:
    description: Allows access to admin commands
    default: op
